import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations);

  static List<String> languages() =>
      ['fr', 'ar', 'en', 'ru', 'es', 'zh_Hans', 'hi', 'tr', 'pt'];

  String get languageCode => locale.languageCode;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.languageCode] ?? '';

  String getVariableText({
    String fr = '',
    String ar = '',
    String en = '',
    String ru = '',
    String es = '',
    String zh_Hans = '',
    String hi = '',
    String tr = '',
    String pt = '',
  }) =>
      [fr, ar, en, ru, es, zh_Hans, hi, tr, pt][languageIndex] ?? '';
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      FFLocalizations.languages().contains(locale.languageCode);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // SignIn
  {
    'jgtruzax': {
      'fr': 'Trouver un partenaire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'iuxqzaus': {
      'fr':
          'Le partenaire que vous cherchez avec la maniere que vous preferez !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '5jjrerod': {
      'fr': 'Connectez-vous via Google',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'u8ceqrn1': {
      'fr': 'Connectez-vous via Apple',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'n3vpdygg': {
      'fr': 'Vous n\'avez pas de compte?',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'tjs7xgjs': {
      'fr': 'S\'inscrire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // Onboarding
  {
    'd2f68ui3': {
      'fr':
          'KWL est la première\napplication conçue \npar une équipe d’experts \nen psychologie et \nspécialistes des relations \nde couple. ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    's11ixzl1': {
      'fr': 'Trouvez votre \npartenaire ideal\navec nous,',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'u3k7yufq': {
      'fr': 'Love for Real !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'p911bmit': {
      'fr': 'Commerncer',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep1
  {
    '8k6ie3sk': {
      'fr': 'Création du votre compte',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'gt7vkk2a': {
      'fr': 'Par Email',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'z42km0y1': {
      'fr': 'Email',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'fqj0yzbm': {
      'fr': 'Mot de passe',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'e4z8ytmt': {
      'fr': 'Confirmez le mot de passe',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'syi85ic2': {
      'fr': 'Créer',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '4frrvv2y': {
      'fr': 'Par Téléphone',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'm0dlzs3r': {
      'fr': 'Votre Téléphone',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'jfb6a30q': {
      'fr': 'Créer',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep2
  {
    'oeoe3l6k': {
      'fr': 'Avatar',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'jpdcya6h': {
      'fr': 'Insérez votre photo',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'wo9oaq4u': {
      'fr': 'Continuez',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep3
  {
    'e4oxhcn1': {
      'fr': 'Base',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '9vdcx824': {
      'fr': 'Nom Complet',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ht2oa9j3': {
      'fr': 'Fonction',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '5j9y9uqq': {
      'fr': 'Présentez-vous !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'kh7tjb9c': {
      'fr': 'Continuez',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep4
  {
    'nlcf25gn': {
      'fr': 'Sexe',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'tb24brgs': {
      'fr': 'Masculin',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ozp4v9m5': {
      'fr': 'Feminin',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'djgnn95q': {
      'fr': 'Date de naissance',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'wj57ucb7': {
      'fr': 'Jour',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '61gljfgg': {
      'fr': 'Mois',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '63amt7r1': {
      'fr': 'Année',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'vdfau4s7': {
      'fr': 'Votre Ville:',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'rxo3jbg1': {
      'fr': 'Ville',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'somnr7cs': {
      'fr': 'Sélectionnez votre pays:',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '9afmd91m': {
      'fr': 'Maroc',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'eapr3xqf': {
      'fr': 'Algérie',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'pk65n8cj': {
      'fr': 'Tunisie',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    't9yzd88w': {
      'fr': 'Libye',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'f8it7sfx': {
      'fr': 'Mauritanie',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'nedwt14c': {
      'fr': 'Egypte',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'u2wowc5b': {
      'fr': 'Saudi Arabia',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '9b4quj22': {
      'fr': 'UAE',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'azj4d96u': {
      'fr': 'Oman',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'z57lorym': {
      'fr': 'Qatar',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'kgyotstk': {
      'fr': 'Bahrain',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'uyecosi8': {
      'fr': 'Kuwait',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'jmebzwjb': {
      'fr': 'Soudan',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'd2hgu81u': {
      'fr': 'Syrie',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'a41foqe4': {
      'fr': 'Liban',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'bc1sw9k4': {
      'fr': 'Turquie',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'a4tlfb4j': {
      'fr': 'Pays',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'hwte74bp': {
      'fr': 'Continuez',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep5
  {
    'jqgzv7gq': {
      'fr': 'Vos Photos',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'fmsmx7ba': {
      'fr': 'veuillez télécharger au moins une de vos photos...',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'c78disd1': {
      'fr': 'Continuez\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep6
  {
    'c5ye6u7t': {
      'fr': 'Questionnaire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'vksprlxx': {
      'fr': '0%',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'x8q1d0fx': {
      'fr':
          'Il est important pour moi de maintenir les valeurs\nou les croyances traditionnelles ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'plyj4lq2': {
      'fr': 'Pas du tout',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'wbf8z75e': {
      'fr': 'Pas vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'vcxsupx4': {
      'fr': 'Vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'rc0ktr4f': {
      'fr': 'Tout à fait \n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '7x6cdcsf': {
      'fr':
          'Il est important pour moi de prendre mes propres\ndécisions en ce qui concerne ma vie ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '04w2ce3p': {
      'fr': 'Pas du tout',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'pvxursmn': {
      'fr': 'Pas vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ngh7531z': {
      'fr': 'Vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'jdbmphar': {
      'fr': 'Tout à fait \n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '4g9k36gl': {
      'fr': 'Continuez\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '0te595dk': {
      'fr': 'Ça suffit pour moi !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep7
  {
    'yj7oaw5w': {
      'fr': 'Questionnaire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'gglth7yf': {
      'fr': '10%',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ksllz08d': {
      'fr':
          'Il est important pour moi d’être la personne la plus\ninfluente dans un couple ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'kbr4i517': {
      'fr': 'Pas du tout',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'z3u5kyvz': {
      'fr': 'Pas vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'kvvkqzcs': {
      'fr': 'Vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'wtsdzneb': {
      'fr': 'Tout à fait \n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    't42rf8ef': {
      'fr':
          'Il est important pour moi de suivre les règles même\nquand personne ne surveille ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'bk3iupzg': {
      'fr': 'Pas du tout',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'd4foqjnl': {
      'fr': 'Pas vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'vv2kj4ta': {
      'fr': 'Vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'lsvv4p73': {
      'fr': 'Tout à fait \n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '6daytfl0': {
      'fr': 'Continuez\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'jykvnlpp': {
      'fr': 'Ça suffit pour moi !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep8
  {
    'mc942bqj': {
      'fr': 'Questionnaire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'pe7k4a3w': {
      'fr': '20%',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'jz9ayuiz': {
      'fr': 'Le plus important dans une relation ?\n (3 choix)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'uewjmka5': {
      'fr': 'La passion',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '48uoxjm9': {
      'fr': 'L\'amour',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'h4lxd1oe': {
      'fr': 'La complicité',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '6h8fr3jl': {
      'fr': 'La loyauté',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ei7fal8z': {
      'fr': 'La fidélité',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ekxocbzk': {
      'fr': 'La transparence',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '41hacv6d': {
      'fr': 'l’authenticité ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'fqmnws25': {
      'fr': 'Continuez\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'yikvi26f': {
      'fr': 'Ça suffit pour moi !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep9
  {
    '4wkntniv': {
      'fr': 'Questionnaire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'qedasp3n': {
      'fr': '30%',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '4zinrync': {
      'fr':
          'Qu’est-ce qui est important pour vous dans une relation amoureuse ? (minimum 5 choix)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ane0kc7c': {
      'fr': 'Ses valeurs',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'tf1lja61': {
      'fr': 'Son énergie',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'zw15di46': {
      'fr': 'L’attachement',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'la2d6xdw': {
      'fr': 'Les habitudes',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'k2v86djq': {
      'fr': 'Le plaisir et la détente',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'cslhflul': {
      'fr': 'Etre à deux',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'rns6d86d': {
      'fr': 'Ma confiance en elle (lui)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ppoaq5g0': {
      'fr': 'Son sex-appeal',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '1b3jsrqr': {
      'fr': 'Son amour pour les enfants',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'xmtwodpr': {
      'fr': 'Le partage',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'lotlreau': {
      'fr': 'Ses convictions',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'kofa4d5x': {
      'fr': 'La passion',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'df1hj2s2': {
      'fr': 'Sa joie de vivre',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'nkyeva9d': {
      'fr': 'Son apparence physique ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'hvwozygw': {
      'fr': 'Notre attirance réciproque ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'hkgwkzgl': {
      'fr': 'Nos similitudes ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ugei4ejz': {
      'fr': 'Continuez\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'hezcwizb': {
      'fr': 'Ça suffit pour moi !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep10
  {
    'ppu4s2x0': {
      'fr': 'Questionnaire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '7682nbj1': {
      'fr': '40%',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'dek18ama': {
      'fr': 'Vos Besoins',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'b88wrl3j': {
      'fr': 'De 1 à 5 (1 pas très important, 10 très important)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ulzkksko': {
      'fr': 'Affection',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'z18sn5vq': {
      'fr': 'Indépendance',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'yflj2fva': {
      'fr': 'Liberté',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'wouevk5m': {
      'fr': 'Reconnaissance',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ysmqc5y7': {
      'fr': 'De 1 à 5 (1 pas très important, 10 très important)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'g6vr4fu1': {
      'fr': 'Admiration ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ljkxmklp': {
      'fr': 'Fonder une famille',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '5ehrybj4': {
      'fr': 'Continuez\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '8fppswdf': {
      'fr': 'Ça suffit pour moi !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep11
  {
    '268nm25r': {
      'fr': 'Questionnaire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '8tb2kgag': {
      'fr': '60%',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'rgdesdex': {
      'fr': 'Quel est votre niveau d’études ?',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'p9swrnq5': {
      'fr': 'Sans diplôme',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ruwhy5ui': {
      'fr': 'Collège',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'z0kbrf7f': {
      'fr': 'BAC ou BAC PRO',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'lbmcfc27': {
      'fr': 'BAC +2 /BAC +3',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '0dfcrqgn': {
      'fr': 'BAC +4 / BAC +5',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '21btpdlo': {
      'fr': 'Doctorat',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'benq6kct': {
      'fr':
          'Quelle importance attachez-vous au niveau d’études de votre partenaire ?',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'whih40fe': {
      'fr': 'Aucune importance',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'm68w14bg': {
      'fr': 'Peu important',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'zspmvdas': {
      'fr': 'Important',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'p0un418b': {
      'fr': 'Plutôt important\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '4lsogzl3': {
      'fr': 'Vraiment important',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '2kw6o9vt': {
      'fr': 'Continuez\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'xejecw3g': {
      'fr': 'Ça suffit pour moi !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep12
  {
    'mwt2fa5y': {
      'fr': 'Questionnaire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '6gmg1s8i': {
      'fr': '70%',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'rcn30c2m': {
      'fr':
          'Imaginez que vos amis devaient vous décrire, quels seraient les adjectifs qui vous correspondraient ? ( choisir 9 adjectifs)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'dd8iw25j': {
      'fr': 'A l’écoute',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'z29y6qpv': {
      'fr': 'Spontané(e)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'hjep3yy1': {
      'fr': 'Optimiste',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '2rrxxm7f': {
      'fr': 'Lunatique',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'k40nxdzl': {
      'fr': 'Rêveur(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'j1qgal09': {
      'fr': 'Calme',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'lpnc7fgw': {
      'fr': 'Empatique',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'za2qsxoy': {
      'fr': 'Fidèle ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '9ko3roze': {
      'fr': 'Logique',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'fciqdeqt': {
      'fr': 'Joyeux(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '1hmyzi7u': {
      'fr': 'Sensible',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '2htoknx5': {
      'fr': 'Engagé(e)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ut46h1fh': {
      'fr': 'Travailleur(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ydnjmmj6': {
      'fr': 'Charmeur(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'aoos0vk8': {
      'fr': 'Energique',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'exg87cvv': {
      'fr': 'Rebel(le)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '3iy8er3c': {
      'fr': 'Enthousiaste',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'cumx4qt2': {
      'fr': 'Consciencieux(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '6coopsc0': {
      'fr': 'Chaleureux(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ar2ojjai': {
      'fr': 'Prend des risques',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'meguzsqc': {
      'fr': 'Respectueux(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ousmsaif': {
      'fr': 'En bonne forme physique',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'rqb98yzm': {
      'fr': 'Digne de confiance',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ive9w04u': {
      'fr': 'Compatissant(e)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'd48ohd78': {
      'fr': 'Continuez\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'qh5slkof': {
      'fr': 'Ça suffit pour moi !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep13
  {
    'hob5p3op': {
      'fr': 'Questionnaire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'wobh1re8': {
      'fr': '80%',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'sueikj41': {
      'fr': 'Je suis spontané(e).',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'q5hazta3': {
      'fr': 'Pas du tout',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '3jajp8fy': {
      'fr': 'Pas vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'bx6idgbl': {
      'fr': 'Vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'aceyrn2r': {
      'fr': 'Tout à fait',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'aqx0bpe8': {
      'fr': 'Il est facile pour moi de discuter avec de nouvelles personnes.',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'urvjj1rs': {
      'fr': 'Pas du tout',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '9efjwy7x': {
      'fr': 'Pas vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '68w5pgmv': {
      'fr': 'Vraiment',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'x5ajn5fe': {
      'fr': 'Tout à fait',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'hhhhcaip': {
      'fr': 'Continuez\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '1ppdc30w': {
      'fr': 'Ça suffit pour moi !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep14
  {
    'ryh79sof': {
      'fr': 'Questionnaire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'vz0jw1ce': {
      'fr': '90%',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '98yt7fto': {
      'fr':
          'Quels seraient les 3 points qui pourraient vous rendre heureux(se) ?\nOuverte ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'sds7x7o4': {
      'fr': 'Continuez\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'yowkqpii': {
      'fr': 'Ça suffit pour moi !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // signupStep15
  {
    'f7d52jsx': {
      'fr': 'Questionnaire',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'wap37wq3': {
      'fr': '100%',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'fvjwmkyq': {
      'fr': 'Vos centres d’intérêts ? \nVeuillez choisir au moins 3 élément.',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'bcriaovm': {
      'fr': 'A l’écoute',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '1b69xkeh': {
      'fr': 'Spontané(e)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'o8g72l2a': {
      'fr': 'Optimiste',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '9mmobbwo': {
      'fr': 'Lunatique',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '6zuig7ie': {
      'fr': 'Rêveur(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'v5qn3fub': {
      'fr': 'Calme',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'kvcpiopt': {
      'fr': 'Empatique',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'mpczer9p': {
      'fr': 'Fidèle ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '9tg8y4mt': {
      'fr': 'Logique',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'e9b53ogp': {
      'fr': 'Joyeux(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'fq14vgiq': {
      'fr': 'Sensible',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'nfxkmeyr': {
      'fr': 'Engagé(e)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ufngl24j': {
      'fr': 'Travailleur(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'nmuj304q': {
      'fr': 'Charmeur(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '2m9ua26w': {
      'fr': 'Energique',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'g4j102fc': {
      'fr': 'Rebel(le)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '6bxnkp8e': {
      'fr': 'Enthousiaste',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ow6h3s22': {
      'fr': 'Consciencieux(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'nz2aay4c': {
      'fr': 'Chaleureux(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '7ydot8ax': {
      'fr': 'Prend des risques',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '9j9gwgp1': {
      'fr': 'Respectueux(se)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'vrhk6bbq': {
      'fr': 'En bonne forme physique',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ygouqb4k': {
      'fr': 'Digne de confiance',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '8iv2y19p': {
      'fr': 'Compatissant(e)',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'e4kbt0wy': {
      'fr': 'Continuez\n',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // HomePage
  {
    'i35bbnpu': {
      'fr': 'Découvrir',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // matches
  {
    'ixqmo3vn': {
      'fr': 'Rencontres',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // isMatch
  {
    'uz3611e0': {
      'fr': 'Rencontres',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ytwpn06z': {
      'fr': 'C\'est un match, ',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'p3qu59hh': {
      'fr': 'Démarrer une conversation maintenant',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'g6bo7zou': {
      'fr': 'ou :',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'sdtqzo74': {
      'fr': 'Ca suffit pour moi !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // Profile
  {
    '13jgokol': {
      'fr': 'Profile',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '0olwx22j': {
      'fr': 'À propos de moi',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'mmsr5n79': {
      'fr': 'Intérêts',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '25o6rp5o': {
      'fr': 'Photos',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // editProfile
  {
    'l3uatqmy': {
      'fr': 'Éditez votre profile',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '2efprkqz': {
      'fr': 'Base',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    't9i89j5t': {
      'fr': 'Nom Complet',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'boqifj1x': {
      'fr': 'Fonction',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'wd9vpqh6': {
      'fr': 'Bio',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'foi3lff4': {
      'fr': 'Sexe',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'l6m6ng3p': {
      'fr': 'Masculin',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'baim5lij': {
      'fr': 'Feminin',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '5bponwwp': {
      'fr': 'Date de naissance',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'jgqgzegq': {
      'fr': 'Jour',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'p5jfzspu': {
      'fr': 'Mois',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'frvjzbxi': {
      'fr': 'Année',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ca4lzles': {
      'fr': 'Votre Ville:',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'h0ueu5id': {
      'fr': 'Ville',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '0jbfg6p4': {
      'fr': 'Sélectionnez votre pays:',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'wod7xith': {
      'fr': 'Maroc',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '11d1afgd': {
      'fr': 'Algérie',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '1cu9v3bt': {
      'fr': 'Tunisie',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '9igd712z': {
      'fr': 'Libye',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'a4vsnbxb': {
      'fr': 'Mauritanie',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'h3hponew': {
      'fr': 'Egypte',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'aj862mpk': {
      'fr': 'Saudi Arabia',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'kc0kivbo': {
      'fr': 'UAE',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ep6joodu': {
      'fr': 'Oman',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '6vdqvewf': {
      'fr': 'Qatar',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'oes0h3he': {
      'fr': 'Bahrain',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'uwb8cyq1': {
      'fr': 'Kuwait',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '8dzu8lug': {
      'fr': 'Soudan',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'uzivxrgd': {
      'fr': 'Syrie',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'cnljsu8m': {
      'fr': 'Liban',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'd9zueiyc': {
      'fr': 'Turquie',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '51j0jlpg': {
      'fr': 'Photos',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'nncrdp48': {
      'fr': 'Enreegistrer',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // notifications
  {
    'asafhaon': {
      'fr': 'Notifications',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'hmqazb5b': {
      'fr': 'Issam a vu votre profile !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '8ft00scz': {
      'fr': 'Dec. 19, 1:30pm - 2:00pm',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // Settings
  {
    'xh8l8uom': {
      'fr': 'Paramètres',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'mvdu5xao': {
      'fr': 'Je recherche:',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'lmv5diaj': {
      'fr': 'Masculin',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'aj7epfo8': {
      'fr': 'Feminin',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'zhp5oi6b': {
      'fr': 'Âge Preference',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'dbjee32m': {
      'fr': 'Location',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'yyfgvofr': {
      'fr': 'Régler',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'dhzpkhfp': {
      'fr': 'Notifications',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '7ns2usao': {
      'fr': 'Nouveaux matchs',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'k8jdlibi': {
      'fr': 'Nouveaux J\'aime',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'b08p41hz': {
      'fr': 'Nouveaux messages',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // chat
  {
    '3oxma931': {
      'fr': 'Group Chat',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // allChatPage
  {
    'aoawbg0t': {
      'fr': 'Chats',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // PhoneVerification
  {
    '4hck5ne8': {
      'fr': 'Code de vérification',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'sr70wzuc': {
      'fr': '_ _ _ _',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'zpaazf5z': {
      'fr': 'Renvoyez',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'qadgfgve': {
      'fr': 'Valider',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'qc2hyg8f': {
      'fr': 'Kais w Leila',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // EmailVerification
  {
    '8ns4unkm': {
      'fr': 'Vérifiez votre boîte de réception.',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'f4eu791m': {
      'fr': 'Confirmez votre email',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ryc80yfx': {
      'fr': '_ _ _ _',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'khkfrltb': {
      'fr': 'Renvoyez !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'p6n1s25t': {
      'fr': 'Valider',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'tsl6cnsy': {
      'fr': 'Kais w Leila',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // background
  {
    'b5wvpplb': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // EmptyChats
  {
    'fh8476sw': {
      'fr': 'Il n\'y a pas des messages !',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
  // Miscellaneous
  {
    'z6sa2e22': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'bwt9iwlk': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '7api57zb': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '1vgkh9hn': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'p7g1hpbb': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ztpxnq81': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'yv11bv53': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'xndhofbj': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'qwjoggxn': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'vrwld95g': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '2x0ests4': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'ejhzf9lt': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'pjtu4eg2': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '9mjte96b': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    'gksbyv5u': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
    '5roz5c8o': {
      'fr': '',
      'ar': '',
      'en': '',
      'es': '',
      'hi': '',
      'pt': '',
      'ru': '',
      'tr': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
